from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional, Dict, Any

app = FastAPI(title="Cortex Backend (Mock Mode)")

# Enable CORS for Power BI Service Iframe
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ChatRequest(BaseModel):
    question: str
    pbi_context: Optional[Dict[str, Any]] = None

@app.get("/")
def home():
    return {
        "status": "Running (Mock Mode)",
        "service": "Snowflake Cortex Backend Mock"
    }

# Explicit preflight handler to prevent 403 Forbidden on OPTIONS requests
@app.options("/chat")
def options_chat():
    return {}

@app.post("/chat")
def chat(request: ChatRequest):
    user_query = request.question
    
    # 1. Parse Power BI Context (Categories/Slicers)
    active_filters_text = "No active filters applied."
    if request.pbi_context and request.pbi_context.get("categories"):
        filters = []
        for cat in request.pbi_context["categories"]:
            col = cat.get("columnName") or cat.get("column")
            vals = cat.get("values") or cat.get("activeValues", [])
            if col and vals:
                filters.append(f"{col} IN ({', '.join(map(str, vals))})")
        if filters:
            active_filters_text = "Filtered by: " + "; ".join(filters)

    # 2. Build Mock Cortex Analyst Interpretation & SQL
    mock_interpretation = (
        f"This is our interpretation of your question:\n\n"
        f"Analyzing '{user_query}' with context [{active_filters_text}]."
    )

    mock_sql = (
        f"-- Mock SQL generated by Cortex Analyst for query: '{user_query}'\n"
        f"SELECT \n"
        f"    brand_name,\n"
        f"    SUM(dollar_sales) AS total_sales,\n"
        f"    COUNT(DISTINCT product_id) AS total_products\n"
        f"FROM CPG.PUBLIC.FACT\n"
        f"WHERE time_period = 'Latest 13 Weeks'\n"
        f"GROUP BY brand_name\n"
        f"ORDER BY total_sales DESC\n"
        f"LIMIT 5;"
    )

    # 3. Build Mock Table Data
    columns = ["BRAND_NAME", "TOTAL_SALES", "TOTAL_PRODUCTS"]
    rows = [
        {"BRAND_NAME": "TYLENOL", "TOTAL_SALES": "$1,245,000", "TOTAL_PRODUCTS": "14"},
        {"BRAND_NAME": "ADVIL", "TOTAL_SALES": "$980,500", "TOTAL_PRODUCTS": "10"},
        {"BRAND_NAME": "MOTRIN", "TOTAL_SALES": "$750,200", "TOTAL_PRODUCTS": "8"},
        {"BRAND_NAME": "ALEVE", "TOTAL_SALES": "$610,000", "TOTAL_PRODUCTS": "6"},
        {"BRAND_NAME": "BENADRYL", "TOTAL_SALES": "$430,800", "TOTAL_PRODUCTS": "5"}
    ]

    return {
        "answer": mock_interpretation,
        "sql": mock_sql,
        "columns": columns,
        "rows": rows,
        "request_id": "mock-req-889922",
        "warnings": []
    }