import os
import json
import requests
import snowflake.connector

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional, Dict, Any


# ==========================================================
# NEW: GEMINI IMPORT - POC
# ==========================================================
# External LLM used temporarily for the POC.
#
# Current:
#     FastAPI -> Gemini API
#
# Future:
#     FastAPI -> Snowflake AI_COMPLETE
#
# This import is intentionally isolated so it can be
# replaced later after approval.
# ==========================================================

from google import genai

# ==========================================================
# END NEW: GEMINI IMPORT - POC
# ==========================================================


# ----------------------------------------------------------
# Load Environment Variables
# ----------------------------------------------------------

load_dotenv()


# ==========================================================
# NEW: GEMINI CLIENT - POC
# ==========================================================
#
# Current implementation:
#     FastAPI -> Gemini
#
# Future implementation:
#     FastAPI -> Snowflake AI_COMPLETE
#
# Required .env:
#
# GEMINI_API_KEY=your_api_key
# GEMINI_MODEL=gemini-2.5-flash
#
# ==========================================================

gemini_client = genai.Client(
    api_key=os.getenv("GEMINI_API_KEY")
)

# ==========================================================
# END NEW: GEMINI CLIENT - POC
# ==========================================================


app = FastAPI(title="Cortex Backend")


# ----------------------------------------------------------
# Enable CORS for Power BI Service Iframe
# ----------------------------------------------------------

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ----------------------------------------------------------
# Request Models
# ----------------------------------------------------------

class ChatRequest(BaseModel):
    question: str
    pbi_context: Optional[Dict[str, Any]] = None


# ----------------------------------------------------------
# Snowflake Connection Utility
# ----------------------------------------------------------

def get_connection():

    return snowflake.connector.connect(

        account=os.getenv(
            "SNOWFLAKE_ACCOUNT"
        ),

        user=os.getenv(
            "SNOWFLAKE_USER"
        ),

        password=os.getenv(
            "SNOWFLAKE_PASSWORD"
        ),

        role=os.getenv(
            "SNOWFLAKE_ROLE"
        ),

        warehouse=os.getenv(
            "SNOWFLAKE_WAREHOUSE"
        ),

        database=os.getenv(
            "SNOWFLAKE_DATABASE"
        ),

        schema=os.getenv(
            "SNOWFLAKE_SCHEMA"
        ),
    )


# ==========================================================
# NEW: GEMINI RESPONSE GENERATOR - POC
# ==========================================================
#
# Purpose:
#
# Generate:
#     1. A concise natural-language answer
#     2. Exactly 3 follow-up questions
#
# IMPORTANT:
#
# We intentionally DO NOT send the actual Snowflake rows.
#
# Gemini receives only:
#
#     - User question
#     - Cortex Analyst interpretation
#     - Returned table schema
#
# Actual result rows remain inside the backend and are
# returned to Power BI separately.
#
# Future:
#
# This entire function can be replaced with Snowflake
# AI_COMPLETE after approval.
#
# ==========================================================

def generate_ai_response(
    user_question: str,
    analyst_answer: str,
    table_schema: list
):

    """
    Generate a concise answer and exactly 3 follow-up
    questions using Gemini.

    Only the table schema is sent to Gemini.
    Actual Snowflake result data is NOT sent.
    """

    # ------------------------------------------------------
    # Gemini model
    # ------------------------------------------------------

    model = os.getenv(
        "GEMINI_MODEL",
        "gemini-2.5-flash"
    )


    # ------------------------------------------------------
    # Prompt
    # ------------------------------------------------------

    prompt = f"""
You are a business analytics assistant inside a Power BI report.

The user asked:

{user_question}

Cortex Analyst interpreted the user's request as:

{analyst_answer}

The SQL query generated by Cortex Analyst returned a table
with the following schema:

{json.dumps(table_schema, indent=2)}

Important restrictions:

- You do NOT have access to the actual rows or values.
- Do NOT invent numbers.
- Do NOT invent brands, retailers, companies, dates, or metrics
  that are not present in the information provided.
- Base your response only on the user's question, Cortex Analyst's
  interpretation, and the returned table schema.

Your responsibilities:

1. Provide a concise answer to the user's question.
2. Since actual data values are not available to you, do not
   make claims about specific values or rankings.
3. Generate exactly 3 useful follow-up questions.
4. Follow-up questions should be relevant to the user's original
   question and the available table schema.
5. Prefer analytical follow-ups involving the available fields,
   such as comparisons, trends, rankings, year-over-year analysis,
   filtering, or breakdowns where appropriate.
6. Do not ask generic questions such as:
   "Would you like more information?"
7. Do not include SQL.
8. Return valid JSON only.

Return exactly this structure:

{{
    "answer": "A concise answer based only on the supplied information",
    "follow_up_questions": [
        "Question 1",
        "Question 2",
        "Question 3"
    ]
}}
"""


    # ------------------------------------------------------
    # Call Gemini
    # ------------------------------------------------------

    try:

        response = gemini_client.models.generate_content(

            model=model,

            contents=prompt,

            config={
                "response_mime_type": "application/json"
            }
        )


        # --------------------------------------------------
        # Extract Gemini response
        # --------------------------------------------------

        result_text = response.text


        # --------------------------------------------------
        # Parse JSON
        # --------------------------------------------------

        result = json.loads(
            result_text
        )


        follow_up_questions = result.get(
            "follow_up_questions",
            []
        )


        # --------------------------------------------------
        # Make sure we never return more than 3
        # --------------------------------------------------

        follow_up_questions = (
            follow_up_questions[:3]
        )


        return {

            "answer":
                result.get(
                    "answer",
                    ""
                ),

            "follow_up_questions":
                follow_up_questions

        }


    except Exception as e:

        raise Exception(
            f"Gemini failed: {str(e)}"
        )


# ==========================================================
# END NEW: GEMINI RESPONSE GENERATOR - POC
# ==========================================================


# ----------------------------------------------------------
# Health Check
# ----------------------------------------------------------

@app.get("/")
def home():

    return {

        "status": "Running",

        "service":
            "Snowflake Cortex Backend"

    }


# ----------------------------------------------------------
# Snowflake Connection Test
# ----------------------------------------------------------

@app.get("/test-connection")
def test_connection():

    try:

        conn = get_connection()

        cursor = conn.cursor()


        cursor.execute(
            "SELECT CURRENT_VERSION()"
        )


        version = cursor.fetchone()[0]


        return {

            "status":
                "Connected",

            "snowflake_version":
                version

        }


    except Exception as e:

        raise HTTPException(

            status_code=500,

            detail=str(e)

        )


    finally:

        if "cursor" in locals():

            cursor.close()


        if "conn" in locals():

            conn.close()


# ==========================================================
# NEW: GEMINI TEST ENDPOINT - POC
# ==========================================================
#
# This endpoint allows you to test Gemini independently
# before testing the complete Cortex Analyst flow.
#
# Once the POC is working, this endpoint can be removed.
#
# ==========================================================

@app.get("/test-gemini")
def test_gemini():

    try:

        model = os.getenv(
            "GEMINI_MODEL",
            "gemini-2.5-flash"
        )


        response = gemini_client.models.generate_content(

            model=model,

            contents=(
                "Say hello in one short sentence."
            )
        )


        return {

            "status":
                "success",

            "model":
                model,

            "response":
                response.text

        }


    except Exception as e:

        raise HTTPException(

            status_code=500,

            detail=str(e)

        )


# ==========================================================
# END NEW: GEMINI TEST ENDPOINT - POC
# ==========================================================


# ----------------------------------------------------------
# Explicit preflight handler
# ----------------------------------------------------------

@app.options("/chat")
def options_chat():

    return {}


# ----------------------------------------------------------
# Live Cortex Chat Endpoint
# ----------------------------------------------------------

@app.post("/chat")
def chat(request: ChatRequest):

    # ======================================================
    # EXISTING CORTEX ANALYST LOGIC
    # ======================================================


    # ------------------------------------------------------
    # 1. Append Power BI context/slicers if available
    # ------------------------------------------------------

    user_query = request.question


    if (
        request.pbi_context
        and request.pbi_context.get("categories")
    ):

        filters = []


        for cat in request.pbi_context["categories"]:

            col = (

                cat.get("columnName")

                or

                cat.get("column")

            )


            vals = (

                cat.get("values")

                or

                cat.get(
                    "activeValues",
                    []
                )

            )


            if col and vals:

                formatted_vals = ", ".join(

                    [
                        f"'{v}'"
                        for v in vals
                    ]

                )


                filters.append(

                    f"{col} IN ({formatted_vals})"

                )


        if filters:

            user_query += (

                f" (Context filters: "

                f"{'; '.join(filters)})"

            )


    # ------------------------------------------------------
    # 2. Construct Cortex Analyst REST Payload
    # ------------------------------------------------------

    account = os.getenv(
        "SNOWFLAKE_ACCOUNT"
    )


    # Clean host URL if user provides account identifier
    # or full host.

    if "snowflakecomputing.com" in account:

        host_url = (
            f"https://{account}"
        )

    else:

        host_url = (

            f"https://"
            f"{account}"
            f".snowflakecomputing.com"

        )


    url = (

        f"{host_url}"
        f"/api/v2/cortex/analyst/message"

    )


    payload = {

        "messages": [

            {

                "role":
                    "user",

                "content": [

                    {

                        "type":
                            "text",

                        "text":
                            user_query

                    }

                ]

            }

        ],

        "semantic_view": os.getenv(

            "SNOWFLAKE_SEMANTIC_VIEW",

            "CPG.PUBLIC.SALES_SEMANTIC"

        )

    }


    headers = {

        "Authorization":
            f"Bearer "
            f"{os.getenv('SNOWFLAKE_PAT')}",

        "Content-Type":
            "application/json",

        "X-Snowflake-Authorization-Token-Type":
            "PROGRAMMATIC_ACCESS_TOKEN"

    }


    # ------------------------------------------------------
    # 3. Call Snowflake Cortex Analyst REST API
    # ------------------------------------------------------

    try:

        response = requests.post(

            url,

            json=payload,

            headers=headers,

            timeout=60

        )


    except Exception as e:

        raise HTTPException(

            status_code=500,

            detail=(

                "Failed to reach Cortex API: "

                f"{str(e)}"

            )

        )


    if response.status_code != 200:

        try:

            error_detail = (
                response.json()
            )

        except Exception:

            error_detail = (
                response.text
            )


        raise HTTPException(

            status_code=
                response.status_code,

            detail=
                error_detail

        )


    data = response.json()


    # ------------------------------------------------------
    # Parse Cortex Analyst response
    # ------------------------------------------------------

    answer_text = ""

    generated_sql = ""


    for item in data.get(

        "message",

        {}

    ).get(

        "content",

        []

    ):

        if item.get("type") == "text":

            answer_text += (

                item.get(
                    "text",
                    ""
                )

                + "\n"

            )


        elif item.get("type") == "sql":

            generated_sql = (

                item.get(
                    "statement",
                    ""
                )

            )


    # ------------------------------------------------------
    # 4. Execute Generated SQL
    # ------------------------------------------------------

    columns = []

    rows = []


    # ======================================================
    # NEW: TABLE SCHEMA FOR GEMINI - POC
    # ======================================================
    #
    # Example:
    #
    # [
    #     {
    #         "name": "BRAND_NAME",
    #         "type": "VARCHAR"
    #     },
    #     {
    #         "name": "DOLLAR_SALES",
    #         "type": "NUMBER"
    #     }
    # ]
    #
    # Only this schema will be sent to Gemini.
    # Actual rows will NOT be sent.
    #
    # ======================================================

    table_schema = []


    # ======================================================
    # END NEW: TABLE SCHEMA FOR GEMINI - POC
    # ======================================================


    if generated_sql:

        try:

            conn = get_connection()

            cursor = conn.cursor()


            cursor.execute(
                generated_sql
            )


            # ------------------------------------------------
            # Extract column headers
            # ------------------------------------------------

            if cursor.description:

                columns = [

                    desc[0]

                    for desc
                    in cursor.description

                ]


                # ==================================================
                # NEW: EXTRACT ONLY TABLE SCHEMA - POC
                # ==================================================
                #
                # cursor.description contains metadata about the
                # returned result columns.
                #
                # We use:
                #
                #     desc[0] -> column name
                #     desc[1] -> Snowflake type
                #
                # We intentionally do NOT send row values.
                #
                # ==================================================

                for desc in cursor.description:

                    column_name = desc[0]


                    column_type = (

                        str(desc[1])

                        if desc[1] is not None

                        else "UNKNOWN"

                    )


                    table_schema.append(

                        {

                            "name":
                                column_name,

                            "type":
                                column_type

                        }

                    )


                # ==================================================
                # END NEW: EXTRACT ONLY TABLE SCHEMA - POC
                # ==================================================


                # ------------------------------------------------
                # Existing behavior:
                # Fetch rows for Power BI table rendering.
                #
                # IMPORTANT:
                # These rows are still returned to Power BI.
                # They are NOT passed to Gemini.
                # ------------------------------------------------

                raw_rows = (
                    cursor.fetchall()
                )


                for row in raw_rows:

                    row_dict = {}


                    for idx, col_name in enumerate(
                        columns
                    ):

                        row_dict[col_name] = (

                            str(row[idx])

                            if row[idx] is not None

                            else ""

                        )


                    rows.append(
                        row_dict
                    )


        except Exception as sql_err:

            answer_text += (

                "\n\n"

                f"*(Note: Generated SQL failed "
                f"to execute: {str(sql_err)})*"

            )


        finally:

            if "cursor" in locals():

                cursor.close()


            if "conn" in locals():

                conn.close()


    # ======================================================
    # NEW: GEMINI RESPONSE GENERATION - POC
    # ======================================================
    #
    # At this point we have:
    #
    #     user question
    #     Cortex Analyst answer
    #     generated SQL
    #     table schema
    #     rows
    #
    # BUT:
    #
    # We send ONLY:
    #
    #     user question
    #     Cortex Analyst answer
    #     table schema
    #
    # to Gemini.
    #
    # The actual rows remain inside your backend and are
    # returned to Power BI as before.
    #
    # ======================================================

    ai_answer = (
        answer_text.strip()
    )

    follow_up_questions = []


    try:

        ai_result = generate_ai_response(

            user_question=
                request.question,

            analyst_answer=
                answer_text.strip(),

            table_schema=
                table_schema

        )


        ai_answer = ai_result.get(

            "answer",

            answer_text.strip()

        )


        follow_up_questions = (

            ai_result.get(

                "follow_up_questions",

                []

            )

        )


        # Safety check:
        # maximum 3 questions.

        follow_up_questions = (

            follow_up_questions[:3]

        )


    except Exception as llm_err:

        print(
            f"Gemini error: {llm_err}"
        )

        raise HTTPException(
            status_code=500,
            detail=f"Gemini failed: {str(llm_err)}"
        )


    # ======================================================
    # END NEW: GEMINI RESPONSE GENERATION - POC
    # ======================================================


    # ======================================================
    # FINAL RESPONSE TO POWER BI
    # ======================================================

    return {

        "answer":
            ai_answer,

        "follow_up_questions":
            follow_up_questions,

        "sql":
            generated_sql,

        "columns":
            columns,

        "rows":
            rows,

        "request_id":
            data.get(
                "request_id"
            ),

        "warnings":
            data.get(
                "warnings",
                []
            )

    }